### ISSUE TITLE
combine only work on the last item

### ISSUE THREAD

**Issue by kldMohammed** [LDRAlighieri/Corbind#9]
i tried to used same code as example does and i found that if i have phone and password in the form only disable button when the last item in combine method is not match the condition 
if the last item matches the condition and i changed phone for wrong phone number for example it doesn't disable button 

here is my code

`
        combine(
            phoneEt.textChanges().map { Patterns.PHONE.matcher(it).matches() },
            passowrdEt.textChanges().map { it.length >= 4 },
            transform = { phone, password -> phone && password }
        ).onEach { loginBtn.isEnabled = it }.launchIn(CoroutineScope(coroutineContext))`

**Comment by LDRAlighieri** [comment]
Hi. Can you give me an example of the correct and incorrect data that you use? I checked a few examples that came to my mind and everything worked correctly. 
In fact, to check, you can simply change the first character of the phone number from `+` to `=` and vice versa. For example, from `+79240000000` to `=79240000000`. This is definitely a pattern violation for `Patterns.PHONE.matcher`

**Comment by kldMohammed** [comment]
I checked with the local phone number Syntax exactly this number 0923382889

When i delete a last number or two also give me the validation is true when the phone number is not i used 1234 to password

**Comment by LDRAlighieri** [comment]
That's right, it should be. Validation is `true` because pattern `Patterns.PHONE` returns `true` for number `092338288` or `09233828` or even `0923382`. Because according to `Patterns.PHONE` these are valid phone numbers.  I think only number `09` will be incorrect in this sequence.
So the `combine` gives you the right result.  If it is important for you that the phone should be at least 10 characters long, you will have to add this check yourself. Or use your own regex.

**Comment by kldMohammed** [comment]
Okay i get it now , and i will check it out
